export const CATEGORY = [{
    CATEGORY: "TAT", SUBCATEGORY: ['SUB_CATEGORY']
},
{
    CATEGORY: "TECH_GENERIC", SUBCATEGORY: ['SUB_CATEGORY']
},
{
    CATEGORY: "VOLUME_CHECK", SUBCATEGORY: ['SUB_CATEGORY']
},
{
    CATEGORY: "MISSING_FOLDEL", SUBCATEGORY: ['SUB_CATEGORY']
},
{
    CATEGORY: "RESCREEN", SUBCATEGORY: ['SUB_CATEGORY']
}
];
export const PRIORITY = ['HIGHT', 'NORMAL']
export const ASSIGN_TO = [
    "ACCESSIONING",
    "ORDER_ENTRY",
    "SPECIMEN_STORAGE",
    "INITIAL_ALIQUOTING",
    "CONFIRMATION_ALIQUATING",
    "MASS_SPEC"]